# Generated by Django 5.1.3 on 2024-11-29 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_desire_goal_event_status_game_koop_game_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='koop',
            new_name='coop',
        ),
        migrations.AlterField(
            model_name='game',
            name='rate',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
