# Generated by Django 5.1.3 on 2024-12-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_alter_idea_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
