# Generated by Django 5.1.3 on 2024-12-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_rename_koop_game_coop_alter_game_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
