# Generated by Django 5.1.3 on 2024-12-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_alter_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
