# Generated by Django 5.1.3 on 2024-12-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_alter_movie_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
